# Generated by Django 4.2.7 on 2024-01-04 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrename', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateField(max_length=20)),
                ('duration', models.IntegerField(null=True)),
                ('summary', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Myapp.genre')),
            ],
        ),
    ]
