# Generated by Django 4.2.7 on 2024-01-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
